version: '3.5'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./:/usr/src/app
    user: '1000'
    links:
      - db

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - php
